
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxidma.h"

/*
* The configuration table for devices
*/

XAxiDma_Config XAxiDma_ConfigTable[XPAR_XAXIDMA_NUM_INSTANCES] =
{
	{
		XPAR_ADC_HIER_AXI_DMA_ADC_DEVICE_ID,
		XPAR_ADC_HIER_AXI_DMA_ADC_BASEADDR,
		XPAR_ADC_HIER_AXI_DMA_ADC_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_ADC_HIER_AXI_DMA_ADC_INCLUDE_MM2S,
		XPAR_ADC_HIER_AXI_DMA_ADC_INCLUDE_MM2S_DRE,
		XPAR_ADC_HIER_AXI_DMA_ADC_M_AXI_MM2S_DATA_WIDTH,
		XPAR_ADC_HIER_AXI_DMA_ADC_INCLUDE_S2MM,
		XPAR_ADC_HIER_AXI_DMA_ADC_INCLUDE_S2MM_DRE,
		XPAR_ADC_HIER_AXI_DMA_ADC_M_AXI_S2MM_DATA_WIDTH,
		XPAR_ADC_HIER_AXI_DMA_ADC_INCLUDE_SG,
		XPAR_ADC_HIER_AXI_DMA_ADC_NUM_MM2S_CHANNELS,
		XPAR_ADC_HIER_AXI_DMA_ADC_NUM_S2MM_CHANNELS,
		XPAR_ADC_HIER_AXI_DMA_ADC_MM2S_BURST_SIZE,
		XPAR_ADC_HIER_AXI_DMA_ADC_S2MM_BURST_SIZE,
		XPAR_ADC_HIER_AXI_DMA_ADC_MICRO_DMA,
		XPAR_ADC_HIER_AXI_DMA_ADC_ADDR_WIDTH,
		XPAR_ADC_HIER_AXI_DMA_ADC_SG_LENGTH_WIDTH
	}
};


