
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_ADC_HIER_AXI_GPIO_LASTMODULO_DEVICE_ID,
		XPAR_ADC_HIER_AXI_GPIO_LASTMODULO_BASEADDR,
		XPAR_ADC_HIER_AXI_GPIO_LASTMODULO_INTERRUPT_PRESENT,
		XPAR_ADC_HIER_AXI_GPIO_LASTMODULO_IS_DUAL
	},
	{
		XPAR_ADC_HIER_AXI_GPIO_RESETFIFO_DEVICE_ID,
		XPAR_ADC_HIER_AXI_GPIO_RESETFIFO_BASEADDR,
		XPAR_ADC_HIER_AXI_GPIO_RESETFIFO_INTERRUPT_PRESENT,
		XPAR_ADC_HIER_AXI_GPIO_RESETFIFO_IS_DUAL
	},
	{
		XPAR_ADC_HIER_AXI_GPIO_START_DEVICE_ID,
		XPAR_ADC_HIER_AXI_GPIO_START_BASEADDR,
		XPAR_ADC_HIER_AXI_GPIO_START_INTERRUPT_PRESENT,
		XPAR_ADC_HIER_AXI_GPIO_START_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_LED_DEVICE_ID,
		XPAR_AXI_GPIO_LED_BASEADDR,
		XPAR_AXI_GPIO_LED_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_LED_IS_DUAL
	}
};


